<?php

namespace Alphavel\Core;

abstract class ServiceProvider
{
    protected Application $app;

    private static bool $facadesCached = false;

    public function __construct(Application $app)
    {
        $this->app = $app;
    }

    abstract public function register(): void;

    public function boot(): void
    {
        //
    }

    public function provides(): array
    {
        return [];
    }

    /**
     * Register facades for this provider
     * Auto-generates facade classes and caches them for OPcache
     *
     * @param array $facades ['Alias' => 'container.key']
     */
    protected function facades(array $facades): void
    {
        if (empty($facades)) {
            return;
        }

        $cacheFile = $this->getFacadeCachePath();

        // Always add facades to cache (merge with existing)
        $this->generateFacadeCache($facades, $cacheFile);

        // Require cache file only once
        if (file_exists($cacheFile) && ! self::$facadesCached) {
            require_once $cacheFile;
            self::$facadesCached = true;
        }
    }

    /**
     * Get the path for facade cache file
     */
    private function getFacadeCachePath(): string
    {
        $storagePath = dirname(__DIR__, 3) . '/storage/framework';

        if (! is_dir($storagePath)) {
            mkdir($storagePath, 0755, true);
        }

        return $storagePath . '/facades.php';
    }

    /**
     * Check if facade cache needs regeneration
     */
    private function facadeCacheNeedsRegeneration(string $cacheFile): bool
    {
        if (! file_exists($cacheFile)) {
            return true;
        }

        // Don't regenerate in production (let OPcache work)
        return false;
    }

    /**
     * Generate facade cache file
     */
    private function generateFacadeCache(array $facades, string $cacheFile): void
    {
        $existingFacades = [];

        // Load existing facades if file exists
        if (file_exists($cacheFile)) {
            $content = file_get_contents($cacheFile);
            preg_match_all('/class (\w+) extends/', $content, $matches);
            $existingFacades = $matches[1] ?? [];
        }

        // Merge new facades with existing
        $allFacades = $this->loadAllFacades($cacheFile);
        $allFacades = array_merge($allFacades, $facades);

        $code = "<?php\n\n";
        $code .= "/**\n";
        $code .= " * Auto-generated Facades\n";
        $code .= " * Generated: " . date('Y-m-d H:i:s') . "\n";
        $code .= " * \n";
        $code .= " * DO NOT EDIT THIS FILE MANUALLY\n";
        $code .= " * Run: php alphavel facade:clear to regenerate\n";
        $code .= " */\n\n";

        foreach ($allFacades as $alias => $accessor) {
            $code .= $this->generateFacadeClass($alias, $accessor);
        }

        file_put_contents($cacheFile, $code);
    }

    /**
     * Load all existing facades from cache
     */
    private function loadAllFacades(string $cacheFile): array
    {
        if (! file_exists($cacheFile)) {
            return [];
        }

        $content = file_get_contents($cacheFile);
        $facades = [];

        // Parse existing facades (multiline regex)
        preg_match_all('/class\s+(\w+)\s+extends[^{]*{[^}]*return\s+[\'"]([^\'"]+)[\'"].*?}/s', $content, $matches);

        if (! empty($matches[1])) {
            foreach ($matches[1] as $index => $alias) {
                $facades[$alias] = $matches[2][$index] ?? '';
            }
        }

        return $facades;
    }

    /**
     * Generate facade class code
     */
    private function generateFacadeClass(string $alias, string $accessor): string
    {
        return <<<PHP
class {$alias} extends \Alphavel\Core\Facade
{
    protected static function getFacadeAccessor(): string
    {
        return '{$accessor}';
    }
}


PHP;
    }
}
