<?php

namespace Alphavel\Core\Console\Commands;

use Alphavel\Core\Console\Command;

/**
 * IDE Helper Generator
 *
 * Gera arquivo _ide_helper.php com autocomplete para:
 * - Facades
 * - Magic methods
 * - Model properties
 */
class IdeHelperCommand extends Command
{
    protected string $signature = 'ide-helper:generate';

    protected string $description = 'Generate IDE helper file for autocomplete';

    public function handle(): int
    {
        $this->info('Generating IDE helper file...');

        $content = $this->generateContent();

        $path = getcwd() . '/_ide_helper.php';
        file_put_contents($path, $content);

        $this->info('✓ IDE helper file generated: _ide_helper.php');
        $this->comment('Add _ide_helper.php to .gitignore if not already present');

        return 0;
    }

    private function generateContent(): string
    {
        $facades = $this->generateFacades();
        $helpers = $this->generateHelpers();

        return <<<PHP
<?php
/**
 * alphavel IDE Helper
 * Generated by: php alphavel ide-helper:generate
 * 
 * This file provides autocomplete support for alphavel framework.
 * Add this file to .gitignore
 */

// ==========================================
// Facades
// ==========================================

$facades

// ==========================================
// Helper Functions
// ==========================================

$helpers

PHP;
    }

    private function generateFacades(): string
    {
        return <<<'PHP'
namespace // Facades removidas - usar app() helper {

    /**
     * @method static \Alphavel\Database\Database getInstance()
     * @method static \PDO getConnection()
     * @method static array query(string $sql, array $bindings = [])
     * @method static mixed queryOne(string $sql, array $bindings = [])
     * @method static int execute(string $sql, array $bindings = [])
     * @method static string|int lastInsertId()
     * @method static bool beginTransaction()
     * @method static bool commit()
     * @method static bool rollback()
     * @method static \QueryBuilder table(string $table)
     * 
     * @see \Alphavel\Database\Database
     */
    class DB extends \Alphavel\Core\Facade {}

    /**
     * @method static mixed get(string $key, mixed $default = null)
     * @method static bool set(string $key, mixed $value, int $ttl = 0)
     * @method static bool has(string $key)
     * @method static bool forget(string $key)
     * @method static bool clear()
     * @method static mixed remember(string $key, int $ttl, callable $callback)
     * @method static mixed pull(string $key, mixed $default = null)
     * @method static int increment(string $key, int $value = 1)
     * @method static int decrement(string $key, int $value = 1)
     * 
     * @see \Alphavel\Database\Cache
     */
    class Cache extends \Alphavel\Core\Facade {}

    /**
     * @method static void info(string $message, array $context = [])
     * @method static void error(string $message, array $context = [])
     * @method static void warning(string $message, array $context = [])
     * @method static void debug(string $message, array $context = [])
     * @method static void log(string $level, string $message, array $context = [])
     * 
     * @see \Alphavel\Core\Logger
     */
    class Log extends \Alphavel\Core\Facade {}

    /**
     * @method static void dispatch(string $event, mixed $data = null)
     * @method static void listen(string $event, callable $listener)
     * @method static array getListeners(string $event)
     * 
     * @see \Alphavel\Core\Event
     */
    class Event extends \Alphavel\Core\Facade {}
}
PHP;
    }

    private function generateHelpers(): string
    {
        return <<<'PHP'
if (!function_exists('app')) {
    /**
     * Get container instance or resolve a service
     * 
     * @param string|null $abstract
     * @return mixed|\Alphavel\Core\Container
     */
    function app(?string $abstract = null) {}
}

if (!function_exists('config')) {
    /**
     * Get configuration value
     * 
     * @param string $key
     * @param mixed $default
     * @return mixed
     */
    function config(string $key, mixed $default = null) {}
}

if (!function_exists('env')) {
    /**
     * Get environment variable
     * 
     * @param string $key
     * @param mixed $default
     * @return mixed
     */
    function env(string $key, mixed $default = null) {}
}

if (!function_exists('cache')) {
    /**
     * Get/set cache value
     * 
     * @param string|null $key
     * @param mixed $value
     * @param int $ttl
     * @return mixed|\Alphavel\Database\Cache
     */
    function cache(?string $key = null, mixed $value = null, int $ttl = 0) {}
}

if (!function_exists('collect')) {
    /**
     * Create a collection from array
     * 
     * @param array $items
     * @return \Alphavel\Core\Collection
     */
    function collect(array $items = []) {}
}

if (!function_exists('dd')) {
    /**
     * Dump and die
     * 
     * @param mixed ...$vars
     * @return never
     */
    function dd(...$vars) {}
}

if (!function_exists('dump')) {
    /**
     * Dump variable
     * 
     * @param mixed ...$vars
     * @return void
     */
    function dump(...$vars) {}
}

if (!function_exists('response')) {
    /**
     * Create response instance
     * 
     * @param mixed $content
     * @param int $status
     * @return \Alphavel\Core\Response
     */
    function response(mixed $content = '', int $status = 200) {}
}

if (!function_exists('json')) {
    /**
     * Create JSON response
     * 
     * @param mixed $data
     * @param int $status
     * @return \Alphavel\Core\Response
     */
    function json(mixed $data, int $status = 200) {}
}

if (!function_exists('redirect')) {
    /**
     * Create redirect response
     * 
     * @param string $url
     * @param int $status
     * @return \Alphavel\Core\Response
     */
    function redirect(string $url, int $status = 302) {}
}

if (!function_exists('abort')) {
    /**
     * Abort with error
     * 
     * @param int $code
     * @param string $message
     * @return never
     */
    function abort(int $code, string $message = '') {}
}

if (!function_exists('view')) {
    /**
     * Render view
     * 
     * @param string $view
     * @param array $data
     * @return string
     */
    function view(string $view, array $data = []) {}
}

if (!function_exists('retry')) {
    /**
     * Retry function N times
     * 
     * @param int $times
     * @param callable $callback
     * @param int $sleep
     * @return mixed
     */
    function retry(int $times, callable $callback, int $sleep = 0) {}
}

if (!function_exists('tap')) {
    /**
     * Tap value and return it
     * 
     * @param mixed $value
     * @param callable $callback
     * @return mixed
     */
    function tap(mixed $value, callable $callback) {}
}

if (!function_exists('value')) {
    /**
     * Return value or execute closure
     * 
     * @param mixed $value
     * @return mixed
     */
    function value(mixed $value) {}
}

if (!function_exists('blank')) {
    /**
     * Check if value is blank
     * 
     * @param mixed $value
     * @return bool
     */
    function blank(mixed $value): bool {}
}

if (!function_exists('filled')) {
    /**
     * Check if value is filled
     * 
     * @param mixed $value
     * @return bool
     */
    function filled(mixed $value): bool {}
}

if (!function_exists('now')) {
    /**
     * Get current timestamp
     * 
     * @return int
     */
    function now(): int {}
}

if (!function_exists('today')) {
    /**
     * Get today's date
     * 
     * @return string
     */
    function today(): string {}
}

if (!function_exists('class_basename')) {
    /**
     * Get class basename
     * 
     * @param string|object $class
     * @return string
     */
    function class_basename(string|object $class): string {}
}
PHP;
    }
}
